# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat Mar 09 18:25:58 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ChopHumanMainWindow(object):
    def setupUi(self, ChopHumanMainWindow):
        ChopHumanMainWindow.setObjectName(_fromUtf8("ChopHumanMainWindow"))
        ChopHumanMainWindow.resize(937, 720)
        self.centralwidget = QtGui.QWidget(ChopHumanMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sceneGraphicsView = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneGraphicsView.sizePolicy().hasHeightForWidth())
        self.sceneGraphicsView.setSizePolicy(sizePolicy)
        self.sceneGraphicsView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sceneGraphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.sceneGraphicsView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.sceneGraphicsView.setObjectName(_fromUtf8("sceneGraphicsView"))
        self.gridLayout.addWidget(self.sceneGraphicsView, 0, 0, 1, 1)
        ChopHumanMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ChopHumanMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        ChopHumanMainWindow.setMenuBar(self.menubar)
        self.toolToolbar = QtGui.QToolBar(ChopHumanMainWindow)
        self.toolToolbar.setIconSize(QtCore.QSize(32, 32))
        self.toolToolbar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolToolbar.setObjectName(_fromUtf8("toolToolbar"))
        ChopHumanMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolToolbar)
        self.statusbar = QtGui.QStatusBar(ChopHumanMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ChopHumanMainWindow.setStatusBar(self.statusbar)
        self.skeletonDockWidget = QtGui.QDockWidget(ChopHumanMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skeletonDockWidget.sizePolicy().hasHeightForWidth())
        self.skeletonDockWidget.setSizePolicy(sizePolicy)
        self.skeletonDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.skeletonDockWidget.setObjectName(_fromUtf8("skeletonDockWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.chkHighlightSelected = QtGui.QCheckBox(self.dockWidgetContents_3)
        self.chkHighlightSelected.setObjectName(_fromUtf8("chkHighlightSelected"))
        self.horizontalLayout_3.addWidget(self.chkHighlightSelected)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.skeletonTreeWidget = QtGui.QTreeWidget(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skeletonTreeWidget.sizePolicy().hasHeightForWidth())
        self.skeletonTreeWidget.setSizePolicy(sizePolicy)
        self.skeletonTreeWidget.setAutoExpandDelay(-1)
        self.skeletonTreeWidget.setObjectName(_fromUtf8("skeletonTreeWidget"))
        self.skeletonTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.skeletonTreeWidget.header().setVisible(False)
        self.verticalLayout_4.addWidget(self.skeletonTreeWidget)
        self.skeletonDockWidget.setWidget(self.dockWidgetContents_3)
        ChopHumanMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.skeletonDockWidget)
        self.animationDockWidget = QtGui.QDockWidget(ChopHumanMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationDockWidget.sizePolicy().hasHeightForWidth())
        self.animationDockWidget.setSizePolicy(sizePolicy)
        self.animationDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.animationDockWidget.setObjectName(_fromUtf8("animationDockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.animationButtonLayout = QtGui.QHBoxLayout()
        self.animationButtonLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.animationButtonLayout.setObjectName(_fromUtf8("animationButtonLayout"))
        self.butNewAnimation = QtGui.QToolButton(self.dockWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/animationNew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butNewAnimation.setIcon(icon)
        self.butNewAnimation.setIconSize(QtCore.QSize(32, 32))
        self.butNewAnimation.setObjectName(_fromUtf8("butNewAnimation"))
        self.animationButtonLayout.addWidget(self.butNewAnimation)
        self.butCloneAnimation = QtGui.QToolButton(self.dockWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/animationClone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butCloneAnimation.setIcon(icon1)
        self.butCloneAnimation.setIconSize(QtCore.QSize(32, 32))
        self.butCloneAnimation.setObjectName(_fromUtf8("butCloneAnimation"))
        self.animationButtonLayout.addWidget(self.butCloneAnimation)
        self.butDeleteAnimation = QtGui.QToolButton(self.dockWidgetContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/animationDelete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butDeleteAnimation.setIcon(icon2)
        self.butDeleteAnimation.setIconSize(QtCore.QSize(32, 32))
        self.butDeleteAnimation.setObjectName(_fromUtf8("butDeleteAnimation"))
        self.animationButtonLayout.addWidget(self.butDeleteAnimation)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.animationButtonLayout.addItem(spacerItem1)
        self.butRetargetAnimation = QtGui.QPushButton(self.dockWidgetContents)
        self.butRetargetAnimation.setObjectName(_fromUtf8("butRetargetAnimation"))
        self.animationButtonLayout.addWidget(self.butRetargetAnimation)
        self.verticalLayout_3.addLayout(self.animationButtonLayout)
        self.animationListWidget = QtGui.QListWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationListWidget.sizePolicy().hasHeightForWidth())
        self.animationListWidget.setSizePolicy(sizePolicy)
        self.animationListWidget.setObjectName(_fromUtf8("animationListWidget"))
        self.verticalLayout_3.addWidget(self.animationListWidget)
        self.animationDockWidget.setWidget(self.dockWidgetContents)
        ChopHumanMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.animationDockWidget)
        self.playbackDockWidget = QtGui.QDockWidget(ChopHumanMainWindow)
        self.playbackDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.playbackDockWidget.setObjectName(_fromUtf8("playbackDockWidget"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.playbackSlider = QtGui.QSlider(self.dockWidgetContents_4)
        self.playbackSlider.setMinimum(0)
        self.playbackSlider.setMaximum(10000)
        self.playbackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playbackSlider.setObjectName(_fromUtf8("playbackSlider"))
        self.horizontalLayout_2.addWidget(self.playbackSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.butZeroPlayback = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butZeroPlayback.sizePolicy().hasHeightForWidth())
        self.butZeroPlayback.setSizePolicy(sizePolicy)
        self.butZeroPlayback.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/gotostart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butZeroPlayback.setIcon(icon3)
        self.butZeroPlayback.setIconSize(QtCore.QSize(32, 32))
        self.butZeroPlayback.setObjectName(_fromUtf8("butZeroPlayback"))
        self.horizontalLayout.addWidget(self.butZeroPlayback)
        self.butMoveToPrevKeyframe = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butMoveToPrevKeyframe.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/prevkey.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butMoveToPrevKeyframe.setIcon(icon4)
        self.butMoveToPrevKeyframe.setIconSize(QtCore.QSize(32, 32))
        self.butMoveToPrevKeyframe.setObjectName(_fromUtf8("butMoveToPrevKeyframe"))
        self.horizontalLayout.addWidget(self.butMoveToPrevKeyframe)
        self.butTogglePlay = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butTogglePlay.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butTogglePlay.setIcon(icon5)
        self.butTogglePlay.setIconSize(QtCore.QSize(32, 32))
        self.butTogglePlay.setCheckable(True)
        self.butTogglePlay.setObjectName(_fromUtf8("butTogglePlay"))
        self.horizontalLayout.addWidget(self.butTogglePlay)
        self.butMoveToNextKeyframe = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butMoveToNextKeyframe.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/nextkey.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butMoveToNextKeyframe.setIcon(icon6)
        self.butMoveToNextKeyframe.setIconSize(QtCore.QSize(32, 32))
        self.butMoveToNextKeyframe.setObjectName(_fromUtf8("butMoveToNextKeyframe"))
        self.horizontalLayout.addWidget(self.butMoveToNextKeyframe)
        self.butEndOfPlayback = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butEndOfPlayback.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/gotoend.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butEndOfPlayback.setIcon(icon7)
        self.butEndOfPlayback.setIconSize(QtCore.QSize(32, 32))
        self.butEndOfPlayback.setObjectName(_fromUtf8("butEndOfPlayback"))
        self.horizontalLayout.addWidget(self.butEndOfPlayback)
        self.labelCurrentFrame = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCurrentFrame.sizePolicy().hasHeightForWidth())
        self.labelCurrentFrame.setSizePolicy(sizePolicy)
        self.labelCurrentFrame.setMinimumSize(QtCore.QSize(75, 0))
        self.labelCurrentFrame.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelCurrentFrame.setFont(font)
        self.labelCurrentFrame.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCurrentFrame.setObjectName(_fromUtf8("labelCurrentFrame"))
        self.horizontalLayout.addWidget(self.labelCurrentFrame)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.spinAnimationLength = QtGui.QSpinBox(self.dockWidgetContents_4)
        self.spinAnimationLength.setSuffix(_fromUtf8(""))
        self.spinAnimationLength.setMaximum(10000)
        self.spinAnimationLength.setObjectName(_fromUtf8("spinAnimationLength"))
        self.horizontalLayout.addWidget(self.spinAnimationLength)
        self.label = QtGui.QLabel(self.dockWidgetContents_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.butLooping = QtGui.QPushButton(self.dockWidgetContents_4)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/looping.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butLooping.setIcon(icon8)
        self.butLooping.setIconSize(QtCore.QSize(32, 32))
        self.butLooping.setCheckable(True)
        self.butLooping.setObjectName(_fromUtf8("butLooping"))
        self.horizontalLayout.addWidget(self.butLooping)
        self.butAddKeyframe = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butAddKeyframe.sizePolicy().hasHeightForWidth())
        self.butAddKeyframe.setSizePolicy(sizePolicy)
        self.butAddKeyframe.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/keyAdd.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butAddKeyframe.setIcon(icon9)
        self.butAddKeyframe.setIconSize(QtCore.QSize(32, 32))
        self.butAddKeyframe.setObjectName(_fromUtf8("butAddKeyframe"))
        self.horizontalLayout.addWidget(self.butAddKeyframe)
        self.butDeleteKeyframe = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butDeleteKeyframe.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/keyDelete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butDeleteKeyframe.setIcon(icon10)
        self.butDeleteKeyframe.setIconSize(QtCore.QSize(32, 32))
        self.butDeleteKeyframe.setObjectName(_fromUtf8("butDeleteKeyframe"))
        self.horizontalLayout.addWidget(self.butDeleteKeyframe)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.playbackDockWidget.setWidget(self.dockWidgetContents_4)
        ChopHumanMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.playbackDockWidget)
        self.toolBar = QtGui.QToolBar(ChopHumanMainWindow)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ChopHumanMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoadImages = QtGui.QAction(ChopHumanMainWindow)
        self.actionLoadImages.setObjectName(_fromUtf8("actionLoadImages"))
        self.actionReset = QtGui.QAction(ChopHumanMainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionTogglePlay = QtGui.QAction(ChopHumanMainWindow)
        self.actionTogglePlay.setObjectName(_fromUtf8("actionTogglePlay"))
        self.actionSelectNextBone = QtGui.QAction(ChopHumanMainWindow)
        self.actionSelectNextBone.setObjectName(_fromUtf8("actionSelectNextBone"))
        self.actionSelectPreviousBone = QtGui.QAction(ChopHumanMainWindow)
        self.actionSelectPreviousBone.setObjectName(_fromUtf8("actionSelectPreviousBone"))
        self.actionFreezeBones = QtGui.QAction(ChopHumanMainWindow)
        self.actionFreezeBones.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/freezeBones.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFreezeBones.setIcon(icon11)
        self.actionFreezeBones.setObjectName(_fromUtf8("actionFreezeBones"))
        self.actionFreezeSkins = QtGui.QAction(ChopHumanMainWindow)
        self.actionFreezeSkins.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/freezeSkins.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFreezeSkins.setIcon(icon12)
        self.actionFreezeSkins.setObjectName(_fromUtf8("actionFreezeSkins"))
        self.menuFile.addAction(self.actionLoadImages)
        self.menuFile.addAction(self.actionReset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionFreezeSkins)
        self.toolBar.addAction(self.actionFreezeBones)

        self.retranslateUi(ChopHumanMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ChopHumanMainWindow)

    def retranslateUi(self, ChopHumanMainWindow):
        ChopHumanMainWindow.setWindowTitle(_translate("ChopHumanMainWindow", "ChopHuman", None))
        self.menuFile.setTitle(_translate("ChopHumanMainWindow", "File", None))
        self.toolToolbar.setWindowTitle(_translate("ChopHumanMainWindow", "toolBar", None))
        self.skeletonDockWidget.setWindowTitle(_translate("ChopHumanMainWindow", "Skeleton", None))
        self.chkHighlightSelected.setText(_translate("ChopHumanMainWindow", "Highlight selected", None))
        self.animationDockWidget.setWindowTitle(_translate("ChopHumanMainWindow", "Animations", None))
        self.butNewAnimation.setToolTip(_translate("ChopHumanMainWindow", "New animation", None))
        self.butNewAnimation.setText(_translate("ChopHumanMainWindow", "New", None))
        self.butCloneAnimation.setToolTip(_translate("ChopHumanMainWindow", "Clone animation", None))
        self.butCloneAnimation.setText(_translate("ChopHumanMainWindow", "Clone", None))
        self.butDeleteAnimation.setToolTip(_translate("ChopHumanMainWindow", "Delete animation", None))
        self.butDeleteAnimation.setText(_translate("ChopHumanMainWindow", "Delete", None))
        self.butRetargetAnimation.setText(_translate("ChopHumanMainWindow", "Retarget", None))
        self.playbackDockWidget.setWindowTitle(_translate("ChopHumanMainWindow", "Playback", None))
        self.butZeroPlayback.setToolTip(_translate("ChopHumanMainWindow", "Go to start", None))
        self.butMoveToPrevKeyframe.setToolTip(_translate("ChopHumanMainWindow", "Previous keyframe", None))
        self.butTogglePlay.setToolTip(_translate("ChopHumanMainWindow", "Toggle play", None))
        self.butMoveToNextKeyframe.setToolTip(_translate("ChopHumanMainWindow", "Next keyframe", None))
        self.butEndOfPlayback.setToolTip(_translate("ChopHumanMainWindow", "Go to end", None))
        self.labelCurrentFrame.setText(_translate("ChopHumanMainWindow", "0", None))
        self.label_2.setText(_translate("ChopHumanMainWindow", "/", None))
        self.label.setText(_translate("ChopHumanMainWindow", "ms", None))
        self.butLooping.setText(_translate("ChopHumanMainWindow", "Loop", None))
        self.butAddKeyframe.setToolTip(_translate("ChopHumanMainWindow", "Add keyframe", None))
        self.butDeleteKeyframe.setToolTip(_translate("ChopHumanMainWindow", "Delete keyframe", None))
        self.toolBar.setWindowTitle(_translate("ChopHumanMainWindow", "toolBar", None))
        self.actionLoadImages.setText(_translate("ChopHumanMainWindow", "Load Images", None))
        self.actionReset.setText(_translate("ChopHumanMainWindow", "Reset", None))
        self.actionTogglePlay.setText(_translate("ChopHumanMainWindow", "Play", None))
        self.actionTogglePlay.setToolTip(_translate("ChopHumanMainWindow", "Toggle play", None))
        self.actionSelectNextBone.setText(_translate("ChopHumanMainWindow", "Select next bone", None))
        self.actionSelectNextBone.setShortcut(_translate("ChopHumanMainWindow", "C", None))
        self.actionSelectPreviousBone.setText(_translate("ChopHumanMainWindow", "Select previous bone", None))
        self.actionSelectPreviousBone.setShortcut(_translate("ChopHumanMainWindow", "V", None))
        self.actionFreezeBones.setText(_translate("ChopHumanMainWindow", "Freeze bones", None))
        self.actionFreezeBones.setToolTip(_translate("ChopHumanMainWindow", "Freeze bones", None))
        self.actionFreezeSkins.setText(_translate("ChopHumanMainWindow", "Freeze skins", None))
        self.actionFreezeSkins.setToolTip(_translate("ChopHumanMainWindow", "Freeze skins", None))

import chophuman_rc
