# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Mar 08 01:14:39 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ChopHumanMainWindow(object):
    def setupUi(self, ChopHumanMainWindow):
        ChopHumanMainWindow.setObjectName(_fromUtf8("ChopHumanMainWindow"))
        ChopHumanMainWindow.resize(834, 654)
        self.centralwidget = QtGui.QWidget(ChopHumanMainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(4, 4, 9, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sceneGraphicsView = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneGraphicsView.sizePolicy().hasHeightForWidth())
        self.sceneGraphicsView.setSizePolicy(sizePolicy)
        self.sceneGraphicsView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.sceneGraphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.sceneGraphicsView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.sceneGraphicsView.setObjectName(_fromUtf8("sceneGraphicsView"))
        self.gridLayout.addWidget(self.sceneGraphicsView, 0, 0, 1, 1)
        ChopHumanMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ChopHumanMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        ChopHumanMainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(ChopHumanMainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ChopHumanMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtGui.QStatusBar(ChopHumanMainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ChopHumanMainWindow.setStatusBar(self.statusbar)
        self.skeletonDockWidget = QtGui.QDockWidget(ChopHumanMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skeletonDockWidget.sizePolicy().hasHeightForWidth())
        self.skeletonDockWidget.setSizePolicy(sizePolicy)
        self.skeletonDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.skeletonDockWidget.setObjectName(_fromUtf8("skeletonDockWidget"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.chkFreezeSkins = QtGui.QCheckBox(self.dockWidgetContents_3)
        self.chkFreezeSkins.setChecked(True)
        self.chkFreezeSkins.setObjectName(_fromUtf8("chkFreezeSkins"))
        self.horizontalLayout_3.addWidget(self.chkFreezeSkins)
        self.chkHighlightSelected = QtGui.QCheckBox(self.dockWidgetContents_3)
        self.chkHighlightSelected.setObjectName(_fromUtf8("chkHighlightSelected"))
        self.horizontalLayout_3.addWidget(self.chkHighlightSelected)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.skeletonTreeWidget = QtGui.QTreeWidget(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.skeletonTreeWidget.sizePolicy().hasHeightForWidth())
        self.skeletonTreeWidget.setSizePolicy(sizePolicy)
        self.skeletonTreeWidget.setAutoExpandDelay(-1)
        self.skeletonTreeWidget.setObjectName(_fromUtf8("skeletonTreeWidget"))
        self.skeletonTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.skeletonTreeWidget.header().setVisible(False)
        self.verticalLayout_4.addWidget(self.skeletonTreeWidget)
        self.skeletonDockWidget.setWidget(self.dockWidgetContents_3)
        ChopHumanMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.skeletonDockWidget)
        self.animationDockWidget = QtGui.QDockWidget(ChopHumanMainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationDockWidget.sizePolicy().hasHeightForWidth())
        self.animationDockWidget.setSizePolicy(sizePolicy)
        self.animationDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.animationDockWidget.setObjectName(_fromUtf8("animationDockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.animationButtonLayout = QtGui.QHBoxLayout()
        self.animationButtonLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.animationButtonLayout.setObjectName(_fromUtf8("animationButtonLayout"))
        self.butNewAnimation = QtGui.QToolButton(self.dockWidgetContents)
        self.butNewAnimation.setObjectName(_fromUtf8("butNewAnimation"))
        self.animationButtonLayout.addWidget(self.butNewAnimation)
        self.butCloneAnimation = QtGui.QToolButton(self.dockWidgetContents)
        self.butCloneAnimation.setObjectName(_fromUtf8("butCloneAnimation"))
        self.animationButtonLayout.addWidget(self.butCloneAnimation)
        self.butDeleteAnimation = QtGui.QToolButton(self.dockWidgetContents)
        self.butDeleteAnimation.setObjectName(_fromUtf8("butDeleteAnimation"))
        self.animationButtonLayout.addWidget(self.butDeleteAnimation)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.animationButtonLayout.addItem(spacerItem)
        self.butRetargetAnimation = QtGui.QPushButton(self.dockWidgetContents)
        self.butRetargetAnimation.setObjectName(_fromUtf8("butRetargetAnimation"))
        self.animationButtonLayout.addWidget(self.butRetargetAnimation)
        self.verticalLayout_3.addLayout(self.animationButtonLayout)
        self.animationListWidget = QtGui.QListWidget(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.animationListWidget.sizePolicy().hasHeightForWidth())
        self.animationListWidget.setSizePolicy(sizePolicy)
        self.animationListWidget.setObjectName(_fromUtf8("animationListWidget"))
        self.verticalLayout_3.addWidget(self.animationListWidget)
        self.animationDockWidget.setWidget(self.dockWidgetContents)
        ChopHumanMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.animationDockWidget)
        self.playbackDockWidget = QtGui.QDockWidget(ChopHumanMainWindow)
        self.playbackDockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.playbackDockWidget.setObjectName(_fromUtf8("playbackDockWidget"))
        self.dockWidgetContents_4 = QtGui.QWidget()
        self.dockWidgetContents_4.setObjectName(_fromUtf8("dockWidgetContents_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.playbackSlider = QtGui.QSlider(self.dockWidgetContents_4)
        self.playbackSlider.setMinimum(0)
        self.playbackSlider.setMaximum(10000)
        self.playbackSlider.setOrientation(QtCore.Qt.Horizontal)
        self.playbackSlider.setObjectName(_fromUtf8("playbackSlider"))
        self.horizontalLayout_2.addWidget(self.playbackSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.butZeroPlayback = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butZeroPlayback.sizePolicy().hasHeightForWidth())
        self.butZeroPlayback.setSizePolicy(sizePolicy)
        self.butZeroPlayback.setObjectName(_fromUtf8("butZeroPlayback"))
        self.horizontalLayout.addWidget(self.butZeroPlayback)
        self.butTogglePlay = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butTogglePlay.setCheckable(True)
        self.butTogglePlay.setObjectName(_fromUtf8("butTogglePlay"))
        self.horizontalLayout.addWidget(self.butTogglePlay)
        self.butEndOfPlayback = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butEndOfPlayback.setObjectName(_fromUtf8("butEndOfPlayback"))
        self.horizontalLayout.addWidget(self.butEndOfPlayback)
        self.chkLooping = QtGui.QCheckBox(self.dockWidgetContents_4)
        self.chkLooping.setObjectName(_fromUtf8("chkLooping"))
        self.horizontalLayout.addWidget(self.chkLooping)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.labelCurrentFrame = QtGui.QLabel(self.dockWidgetContents_4)
        self.labelCurrentFrame.setObjectName(_fromUtf8("labelCurrentFrame"))
        self.horizontalLayout.addWidget(self.labelCurrentFrame)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.spinAnimationLength = QtGui.QSpinBox(self.dockWidgetContents_4)
        self.spinAnimationLength.setSuffix(_fromUtf8(""))
        self.spinAnimationLength.setMaximum(10000)
        self.spinAnimationLength.setObjectName(_fromUtf8("spinAnimationLength"))
        self.horizontalLayout.addWidget(self.spinAnimationLength)
        self.label = QtGui.QLabel(self.dockWidgetContents_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.butMoveToPrevKeyframe = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butMoveToPrevKeyframe.setObjectName(_fromUtf8("butMoveToPrevKeyframe"))
        self.horizontalLayout.addWidget(self.butMoveToPrevKeyframe)
        self.butMoveToNextKeyframe = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butMoveToNextKeyframe.setObjectName(_fromUtf8("butMoveToNextKeyframe"))
        self.horizontalLayout.addWidget(self.butMoveToNextKeyframe)
        self.butAddKeyframe = QtGui.QPushButton(self.dockWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.butAddKeyframe.sizePolicy().hasHeightForWidth())
        self.butAddKeyframe.setSizePolicy(sizePolicy)
        self.butAddKeyframe.setObjectName(_fromUtf8("butAddKeyframe"))
        self.horizontalLayout.addWidget(self.butAddKeyframe)
        self.butDeleteKeyframe = QtGui.QPushButton(self.dockWidgetContents_4)
        self.butDeleteKeyframe.setObjectName(_fromUtf8("butDeleteKeyframe"))
        self.horizontalLayout.addWidget(self.butDeleteKeyframe)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.playbackDockWidget.setWidget(self.dockWidgetContents_4)
        ChopHumanMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.playbackDockWidget)
        self.actionLoadImages = QtGui.QAction(ChopHumanMainWindow)
        self.actionLoadImages.setObjectName(_fromUtf8("actionLoadImages"))
        self.actionReset = QtGui.QAction(ChopHumanMainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionTogglePlay = QtGui.QAction(ChopHumanMainWindow)
        self.actionTogglePlay.setObjectName(_fromUtf8("actionTogglePlay"))
        self.menuFile.addAction(self.actionLoadImages)
        self.menuFile.addAction(self.actionReset)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ChopHumanMainWindow)
        QtCore.QMetaObject.connectSlotsByName(ChopHumanMainWindow)

    def retranslateUi(self, ChopHumanMainWindow):
        ChopHumanMainWindow.setWindowTitle(_translate("ChopHumanMainWindow", "ChopHuman", None))
        self.menuFile.setTitle(_translate("ChopHumanMainWindow", "File", None))
        self.toolBar.setWindowTitle(_translate("ChopHumanMainWindow", "toolBar", None))
        self.skeletonDockWidget.setWindowTitle(_translate("ChopHumanMainWindow", "Skeleton", None))
        self.chkFreezeSkins.setText(_translate("ChopHumanMainWindow", "Freeze skins", None))
        self.chkHighlightSelected.setText(_translate("ChopHumanMainWindow", "Highlight selected", None))
        self.animationDockWidget.setWindowTitle(_translate("ChopHumanMainWindow", "Animations", None))
        self.butNewAnimation.setText(_translate("ChopHumanMainWindow", "New", None))
        self.butCloneAnimation.setText(_translate("ChopHumanMainWindow", "Clone", None))
        self.butDeleteAnimation.setText(_translate("ChopHumanMainWindow", "Delete", None))
        self.butRetargetAnimation.setText(_translate("ChopHumanMainWindow", "Retarget", None))
        self.playbackDockWidget.setWindowTitle(_translate("ChopHumanMainWindow", "Playback", None))
        self.butZeroPlayback.setText(_translate("ChopHumanMainWindow", "<<", None))
        self.butTogglePlay.setText(_translate("ChopHumanMainWindow", "Play", None))
        self.butEndOfPlayback.setText(_translate("ChopHumanMainWindow", ">>", None))
        self.chkLooping.setText(_translate("ChopHumanMainWindow", "Looping", None))
        self.labelCurrentFrame.setText(_translate("ChopHumanMainWindow", "0", None))
        self.label_2.setText(_translate("ChopHumanMainWindow", "/", None))
        self.label.setText(_translate("ChopHumanMainWindow", "ms", None))
        self.butMoveToPrevKeyframe.setText(_translate("ChopHumanMainWindow", "<< Prev key", None))
        self.butMoveToNextKeyframe.setText(_translate("ChopHumanMainWindow", "Next key >>", None))
        self.butAddKeyframe.setText(_translate("ChopHumanMainWindow", "Add key", None))
        self.butDeleteKeyframe.setText(_translate("ChopHumanMainWindow", "Delete key", None))
        self.actionLoadImages.setText(_translate("ChopHumanMainWindow", "Load Images", None))
        self.actionReset.setText(_translate("ChopHumanMainWindow", "Reset", None))
        self.actionTogglePlay.setText(_translate("ChopHumanMainWindow", "Play", None))
        self.actionTogglePlay.setToolTip(_translate("ChopHumanMainWindow", "Toggle play", None))

